name: Deploy Dgx on QA local machine

on:
  push:
    branches:
      - uat
    paths:
      'server/**'


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install Frontend Dependancies
        working-directory: server/client
        run: npm install

      - name: Build Frontend
        working-directory: server/client
        run: npm run build

      - name: Setup Ssh Agent 
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_QA }}

      - name: Deploy Code to QA
        run: |
          rsync -avz --delete
            --exclude="node_modules" \
            --exclude=".git" \
            -e "ssh -o StrictHostKeyChecking=no" \
            server/ \
            ${{ secrets.SERVER_USER_QA }}@${{ secrets.SERVER_HOST_QA }}:${{ secrets.APP_DIR }}

      - name: Restart Uat Application
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER_QA }}@${{ secrets.SERVER_HOST_QA }} << 'EOF'
              cd ${{ secrets.APP_DIR }}
              npm install --omit=dev
              pm2 delete qa-app || true
              pm2 start npm --name 'qa-app' -- start
              pm2 save
          EOF
