name: Build and Deploy of Uat

on:
  push:
    branches:
      - uat
    paths:
      - '/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkoout code from repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Frontend Dependeacy
        working-directory: ./server/client
        run: npm ci

      - name: Build Frontend
        working-directory: ./server/client
        run: ci=false npm run build

      - name: Install Backend Dependancy
        working-directory: ./server
        run: npm ci

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_UAT }}

      - name: Add Host to KnownHost
        run: |
          rsync -avz --delete  \
            --exclude="node_modules"  \
            --exclude=".git"  \
            -e "ssh -o StrictHostKeyChecking=no"  \
            ./server/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.APP_DIR }}/

      - name: Restart Application on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}  << 'EOF'
            cd ${{ secrets.APP_DIR }}
            npm ci --production
            pm2 del all
            pm2 start npm -- start
          EOF
